version: '3'
services:
  elastic:
    container_name: nikita-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  postgres:
    container_name: nikita-postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nikita_user
      - POSTGRES_PASSWORD=N1k1t4
      - POSTGRES_DB=nikita
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  nikita:
    depends_on:
      elastic:
        condition: service_started
      postgres:
        condition: service_healthy
    image: arkivverket.azurecr.io/da-nikita/nikita-noark5-core:0.7
    ports:
      - "8092:8092"
    environment:
      - DB_URI=jdbc:postgresql://nikita-postgres:5432/nikita
      - DB_USER=nikita_user
      - DB_PASS=N1k1t4
      - ELASTIC_URI=http://nikita-elastic:9200
      - ELASTIC_USER=elastic
      - ELASTIC_PASS=hQ98IjdXNBC00SS79yEe5207
      - NIKITA_BASE_DIR=/tmp
      - spring.profiles.active=postgres
      - nikita.import.allowed=true
