package nikita.common.util.serializers.noark5v5.hateoas;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import nikita.common.model.noark5.v5.hateoas.HateoasNoarkObject;
import nikita.common.model.noark5.v5.interfaces.entities.INikitaEntity;
import nikita.common.util.exceptions.NikitaMisconfigurationException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.constraints.NotNull;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.List;

import static nikita.common.config.Constants.ENTITY_ROOT_NAME_LIST;
import static nikita.common.config.Constants.ENTITY_ROOT_NAME_LIST_COUNT;
import static nikita.common.util.CommonUtils.Hateoas.Serialize.printHateoasLinks;


/**
 * Created by tsodring on 2/9/17.
 */
public class HateoasSerializer
        extends StdSerializer<HateoasNoarkObject> {

    private static final Logger logger =
            LoggerFactory.getLogger(HateoasSerializer.class);

    public HateoasSerializer() {
        super(HateoasNoarkObject.class);
    }

    @Override
    public void serialize(
            HateoasNoarkObject hateoasObject, JsonGenerator jgen,
            SerializerProvider provider)
            throws IOException {
        // For lists the output should be
        //  { "entity": [], "_links": [] }
        // An empty list should produce
        // { "entity": [], "_links": [] }
        // An entity should produce
        // { "field" : "value", "_links": [] }
        // No such thing as an empty entity
        List<INikitaEntity> list = hateoasObject.getList();
        if (list.size() > 0) {
            if (!hateoasObject.isSingleEntity()) {
                jgen.writeStartObject();
                jgen.writeFieldName(ENTITY_ROOT_NAME_LIST);
                jgen.writeStartArray();
            }
            for (INikitaEntity entity : list) {
                serializeNoarkEntity(entity, hateoasObject, jgen);
            }
            if (!hateoasObject.isSingleEntity()) {
                jgen.writeEndArray();
                printHateoasLinks(jgen, hateoasObject.getSelfLinks());
                jgen.writeEndObject();
            }
        }
        // It's an empty object, so just returning Hateoas self links
        else {
            jgen.writeStartObject();
            jgen.writeNumberField(ENTITY_ROOT_NAME_LIST_COUNT, 0);
            printHateoasLinks(jgen, hateoasObject.getSelfLinks());
            jgen.writeEndObject();
        }
    }

    protected void serializeNoarkEntity(
            INikitaEntity entity, HateoasNoarkObject hateoasObject,
            JsonGenerator jgen) throws IOException {
    }

    @Override
    public JsonNode getSchema(SerializerProvider provider, Type typeHint) {
        throw new UnsupportedOperationException();
    }


    protected void printNullable(JsonGenerator jgen,
                                 String fieldName, String value)
            throws IOException {
        jgen.writeStringField(fieldName, value);
    }

    protected void printNullable(JsonGenerator jgen,
                                 String fieldName, Integer value)
            throws IOException {
        jgen.writeNumberField(fieldName, value);
    }

    protected void printNullable(JsonGenerator jgen,
                                 String fieldName, Double value)
            throws IOException {
        jgen.writeNumberField(fieldName, value);
    }

    /**
     * Print a field / value pair, but throw exception if the value is
     * mandatory. This is required so that we can capture illegal payloads being
     * generated by nikita.
     *
     * @param jgen
     * @param fieldName
     * @param value
     * @throws IOException
     */
    protected void print(JsonGenerator jgen,
                         String fieldName, @NotNull String value)
            throws IOException {
        checkNull(fieldName, value);
        jgen.writeStringField(fieldName, value);
    }

    protected void print(JsonGenerator jgen,
                         String fieldName, @NotNull Integer value)
            throws IOException {
        checkNull(fieldName, value);
        jgen.writeNumberField(fieldName, value);
    }

    protected void print(JsonGenerator jgen,
                         String fieldName, @NotNull Double value)
            throws IOException {
        checkNull(fieldName, value);
        jgen.writeNumberField(fieldName, value);
    }

    private void checkNull(String fieldName, Object value) {
        if (null == value) {
            String msg = "When serialising [" + fieldName + "], there was no " +
                    "associated value. This field is mandatory";
            logger.error(msg);
            throw new NikitaMisconfigurationException(msg);
        }
    }
}
