# ===================================================================
# Postgres-specific configuration
# ===================================================================

spring:
  application:
    name: OsloMet Noark 5 Core (using Postgres)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://localhost:5432/nikita}
    username: ${DB_USER:INSERT-USERNAME-HERE}
    password: ${DB_PASS:INSERT-PASSWORD-HERE}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        hbm2ddl:
          auto: create
      discriminator.ignore_explicit_for_joined: true
      org.hibernate.envers.audit_table_prefix: aud_
