# ===================================================================
# Spring Boot configuration for the default profile.
#
# ===================================================================
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#      hibernate:
#        SQL: DEBUG

server:
  servlet:
    context-path: /noark5v5
  port: 8092


spring:
  h2:
    console:
      path: /h2-console
  application:
    name: OsloMet Noark 5 Core (Demo mode)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:n5DemoDb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        hbm2ddl:
          auto: create-drop
          hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        discriminator.ignore_explicit_for_joined: true
        org.hibernate.envers.audit_table_prefix: aud_

logging:
  level:
    org:
      reflections: OFF

security:
  oauth2:
    client:
      client-id: nikita-client
      client-secret: $2a$10$52VgSTgNvk4ROc8YNYdTUesHhQTm2r5oeH1aiCtIgu3rfPQZQzswa
      token-expiry: 28800 # seconds
info:
  app.name: OsloMet Noark 5 Core
  build.version: ${project.version}

nikita:
  system:
    vendor:
      name: OsloMet
      version: 0.4
    protocol:
      version: Noark 5.5.0
    build: 2019-08-07+0200
  startup:
    create-demo-users: true # Populate database with some users
    create-directory-store: true # If not created, attempt to create
    directory-store-name: /data2/nikita/storage/ # Where to store documents
    incoming-directory: /data2/nikita/storage/incoming/ # Temporary storage area
  application:
    pagination:
      max-page-size: 10 # Set number of results per page. Currently not used
    checksum-algorithm: SHA-256
  server:
    hateoas:
      publicAddress: http://localhost:8092
    details:
      conformity-levels:
        official: arkivstruktur, casehandling, metadata
        non-official: gui, import-api
  # Only used if eventhandling profile is enabled
  simplechain:
    # Address to post a block to the chain.
    address: http://localhost:9792:/simplechain/block
