# ===================================================================
# Spring Boot configuration for the "mysql" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
#
# To get the database working right, be administrator in mysql and
#
#    GRANT ALL ON nikita_noark5_prod.* to  'INSERT-USERNAME-HERE'@'%' identified by 'INSERT-PASSWORD-HERE';
#    flush privileges;
#    create database nikita_noark5_prod;
#
# Or whatever variation you use to create a user
# ===================================================================
server:
  application:
    name: OsloMet Noark 5 Core (using MySQL)
  servlet:
    context-path: /noark5v4
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nikita_noark5_prod
    username: INSERT-USERNAME-HERE
    password: INSERT-PASSWORD-HERE
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
          import_files: db/noark5_metadata_values.sql,db/postcode.sql,db/countrycode.sql
          #import_files: db/h2/import.sql,db/noark5_metadata_values.sql,
          #db/postcode.sql,db/countrycode.sql
#        show_sql: true # Slows things down if this is enabled.
        hbm2ddl.auto: create-drop
        #hbm2ddl.auto: validate
    database: mysql
  profiles:
    active: security-oauth2-authentication, mysql

security:
  oauth2:
    client:
      client-id: nikita-client
      client-secret: $2a$10$52VgSTgNvk4ROc8YNYdTUesHhQTm2r5oeH1aiCtIgu3rfPQZQzswa

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
management:
  server:
    servlet:
      context-path: /management
info:
    app.name: HiOA Noark 5 Core (Demo version)
    build.version: ${project.version}
# Make sure there is a slash at the end of the address
hateoas:
    publicAddress: http://localhost:8092/noark5v4/

# ===================================================================
# nikita-noark5-core specific properties
# ===================================================================

# Application properties
application:
  pagination:
    max-page-size: 10


nikita:
  startup:
    create-demo-users: true
    create-directory-store: true
    directory-store-name: /data/nikita/storage/
    incoming-directory: /data/nikita/storage/incoming/
  application:
    pagination:
      max-page-size: 10
    checksum-algorithm: SHA-256
  server:
    name: localhost
    hateoas:
      publicAddress: http://localhost:8092/noark5v4/ # Make sure there is a slash at the end of the address
    details:
      conformity-levels:
        official: arkivstruktur, casehandling, metadata
        non-official: gui, import-api

