# ===================================================================
# Spring Boot configuration for the "ci" profile.
# Supplements the JPA configuration by modifying the elasticsearch
# host URI for execution in the CI environment.
# ===================================================================

spring:
  jpa:
    properties:
      hibernate:
        search:
          backend:
            uris: ${ELASTIC_URI:http://elasticsearch:9200}
