# Spring Boot configuration for the "postgres" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

server:
  servlet:
    context-path: /noark5v4
  port: 8092

spring:
  application:
    name: OsloMet Noark 5 Core (using Postgres)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nikita_noark5_prod
    username: INSERT-USERNAME-HERE
    password: INSERT-PASSWORD-HERE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: false
    properties:
      hibernate.hbm2ddl.auto: validate
      hibernate.discriminator.ignore_explicit_for_joined: true

  profiles:
    active: security-oauth2-authentication, postgres

security:
  oauth2:
    client:
      client-id: nikita-client
      client-secret: $2a$10$52VgSTgNvk4ROc8YNYdTUesHhQTm2r5oeH1aiCtIgu3rfPQZQzswa
      token-expiry: 28800 # seconds

info:
  app.name: OsloMet Noark 5 Core
  build.version: ${project.version}

nikita:
  startup:
    create-demo-users: false # Populate database with some users
    create-directory-store: true # If not created, attempt to create
    directory-store-name: /data/nikita/storage/ # Where to store documents
    incoming-directory: /data/nikita/storage/incoming/ # Temporary storage area
  application:
    pagination:
      max-page-size: 10 # Set number of results per page. Currently not used
    checksum-algorithm: SHA-256
  server:
    hateoas:
      publicAddress: http://localhost:8092
    details:
      conformity-levels:
        official: arkivstruktur, casehandling, metadata
        non-official: gui, import-api
  # Only used if eventhandling profile is enabled
  simplechain:
    # Address to post a block to the chain.
    address: http://localhost:9792:/simplechain/block
