# Spring Boot configuration for the "postgres" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

server:
  application:
    name: OsloMet Noark 5 Core (using Postgres)
  servlet:
    context-path: /noark5v4
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nikita_noark5_prod
    username: INSERT-USERNAME-HERE
    password: INSERT-PASSWORD-HERE
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialec
    properties:
      hbm2ddl:
        import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        import_files: db/noark5_metadata_values.sql,db/postcode.sql,db/countrycode.sql
        #import_files: db/h2/import.sql,db/noark5_metadata_values.sql,
        #db/postcode.sql,db/countrycode.sql
      #        show_sql: true # Slows things down if this is enabled.
        auto: validate
    database: postgresql
  profiles:
    active: security-oauth2-authentication, postgres

hibernate:
  discriminator:
    ignore_explicit_for_joined: true

security:
  oauth2:
    client:
      client-id: nikita-client
      client-secret: $2a$10$52VgSTgNvk4ROc8YNYdTUesHhQTm2r5oeH1aiCtIgu3rfPQZQzswa
      token-expiry: 28800 # seconds

info:
  app.name: OsloMet Noark 5 Core (Postgres)
  build.version: ${project.version}


# Make sure there is a slash at the end of the address
hateoas:
    publicAddress: http://localhost:8092/noark5v4/

# ===================================================================
# nikita-noark5-core specific properties
# ===================================================================

# Application properties
application:
  pagination:
    max-page-size: 10

# We will move all application properties here. Just need to make the code
# in sync with these properties. That's why they are duplicated
nikita:
  startup:
    create-demo-users: true
    create-directory-store: true
    directory-store-name: /data/nikita/storage/
    incoming-directory: /data/nikita/storage/incoming/
  application:
    pagination:
      max-page-size: 10
    checksum-algorithm: SHA-256
  server:
    name: localhost
    hateoas:
      publicAddress: http://localhost:8092/noark5v4/ # Make sure there is a slash at the end of the address
    details:
      conformity-levels:
        official: arkivstruktur, casehandling, metadata
        non-official: gui, import-api
