//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ansvarlig complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Ansvarlig">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Felles/Filter/xml.schema/2012.01.31}Kriterie">
 *       &lt;sequence>
 *         &lt;element name="eier" type="{http://rep.geointegrasjon.no/Felles/Filter/xml.schema/2012.01.31}AnsvarligEnum"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ansvarlig", namespace = "http://rep.geointegrasjon.no/Felles/Filter/xml.schema/2012.01.31", propOrder = {
        "eier"
})
public class Ansvarlig
        extends Kriterie {

    @XmlElement(required = true)
    protected AnsvarligEnum eier;

    /**
     * Gets the value of the eier property.
     *
     * @return possible object is
     * {@link AnsvarligEnum }
     */
    public AnsvarligEnum getEier() {
        return eier;
    }

    /**
     * Sets the value of the eier property.
     *
     * @param value allowed object is
     *              {@link AnsvarligEnum }
     */
    public void setEier(AnsvarligEnum value) {
        this.eier = value;
    }

}
