//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Avskrivning complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Avskrivning">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="systemID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="avskrivningsdato" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="avskrevetAv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="avskrivningsmaate" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}Avskrivningsmaate" minOccurs="0"/>
 *         &lt;element name="referanseAvskriverJournalnummer" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}Journalnummer" minOccurs="0"/>
 *         &lt;element name="referanseAvskrivesAvJournalnummer" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}Journalnummer" minOccurs="0"/>
 *         &lt;element name="referanseAvskriverEksternNoekkel" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}EksternNoekkel" minOccurs="0"/>
 *         &lt;element name="referanseAvskrivesAvEksternNoekkel" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}EksternNoekkel" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Avskrivning", namespace = "http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31", propOrder = {
        "systemID",
        "avskrivningsdato",
        "avskrevetAv",
        "avskrivningsmaate",
        "referanseAvskriverJournalnummer",
        "referanseAvskrivesAvJournalnummer",
        "referanseAvskriverEksternNoekkel",
        "referanseAvskrivesAvEksternNoekkel"
})
public class Avskrivning {

    protected String systemID;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar avskrivningsdato;
    protected String avskrevetAv;
    protected Avskrivningsmaate avskrivningsmaate;
    protected Journalnummer referanseAvskriverJournalnummer;
    protected Journalnummer referanseAvskrivesAvJournalnummer;
    protected EksternNoekkel referanseAvskriverEksternNoekkel;
    protected EksternNoekkel referanseAvskrivesAvEksternNoekkel;

    /**
     * Gets the value of the systemID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSystemID() {
        return systemID;
    }

    /**
     * Sets the value of the systemID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSystemID(String value) {
        this.systemID = value;
    }

    /**
     * Gets the value of the avskrivningsdato property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getAvskrivningsdato() {
        return avskrivningsdato;
    }

    /**
     * Sets the value of the avskrivningsdato property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setAvskrivningsdato(XMLGregorianCalendar value) {
        this.avskrivningsdato = value;
    }

    /**
     * Gets the value of the avskrevetAv property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAvskrevetAv() {
        return avskrevetAv;
    }

    /**
     * Sets the value of the avskrevetAv property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAvskrevetAv(String value) {
        this.avskrevetAv = value;
    }

    /**
     * Gets the value of the avskrivningsmaate property.
     *
     * @return possible object is
     * {@link Avskrivningsmaate }
     */
    public Avskrivningsmaate getAvskrivningsmaate() {
        return avskrivningsmaate;
    }

    /**
     * Sets the value of the avskrivningsmaate property.
     *
     * @param value allowed object is
     *              {@link Avskrivningsmaate }
     */
    public void setAvskrivningsmaate(Avskrivningsmaate value) {
        this.avskrivningsmaate = value;
    }

    /**
     * Gets the value of the referanseAvskriverJournalnummer property.
     *
     * @return possible object is
     * {@link Journalnummer }
     */
    public Journalnummer getReferanseAvskriverJournalnummer() {
        return referanseAvskriverJournalnummer;
    }

    /**
     * Sets the value of the referanseAvskriverJournalnummer property.
     *
     * @param value allowed object is
     *              {@link Journalnummer }
     */
    public void setReferanseAvskriverJournalnummer(Journalnummer value) {
        this.referanseAvskriverJournalnummer = value;
    }

    /**
     * Gets the value of the referanseAvskrivesAvJournalnummer property.
     *
     * @return possible object is
     * {@link Journalnummer }
     */
    public Journalnummer getReferanseAvskrivesAvJournalnummer() {
        return referanseAvskrivesAvJournalnummer;
    }

    /**
     * Sets the value of the referanseAvskrivesAvJournalnummer property.
     *
     * @param value allowed object is
     *              {@link Journalnummer }
     */
    public void setReferanseAvskrivesAvJournalnummer(Journalnummer value) {
        this.referanseAvskrivesAvJournalnummer = value;
    }

    /**
     * Gets the value of the referanseAvskriverEksternNoekkel property.
     *
     * @return possible object is
     * {@link EksternNoekkel }
     */
    public EksternNoekkel getReferanseAvskriverEksternNoekkel() {
        return referanseAvskriverEksternNoekkel;
    }

    /**
     * Sets the value of the referanseAvskriverEksternNoekkel property.
     *
     * @param value allowed object is
     *              {@link EksternNoekkel }
     */
    public void setReferanseAvskriverEksternNoekkel(EksternNoekkel value) {
        this.referanseAvskriverEksternNoekkel = value;
    }

    /**
     * Gets the value of the referanseAvskrivesAvEksternNoekkel property.
     *
     * @return possible object is
     * {@link EksternNoekkel }
     */
    public EksternNoekkel getReferanseAvskrivesAvEksternNoekkel() {
        return referanseAvskrivesAvEksternNoekkel;
    }

    /**
     * Sets the value of the referanseAvskrivesAvEksternNoekkel property.
     *
     * @param value allowed object is
     *              {@link EksternNoekkel }
     */
    public void setReferanseAvskrivesAvEksternNoekkel(EksternNoekkel value) {
        this.referanseAvskrivesAvEksternNoekkel = value;
    }

}
