//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BboxKriterie complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BboxKriterie">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Felles/Filter/xml.schema/2012.01.31}Kriterie">
 *       &lt;sequence>
 *         &lt;element name="bbox" type="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}Bbox"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BboxKriterie", namespace = "http://rep.geointegrasjon.no/Felles/Filter/xml.schema/2012.01.31", propOrder = {
        "bbox"
})
public class BboxKriterie
        extends Kriterie {

    @XmlElement(required = true)
    protected Bbox bbox;

    /**
     * Gets the value of the bbox property.
     *
     * @return possible object is
     * {@link Bbox }
     */
    public Bbox getBbox() {
        return bbox;
    }

    /**
     * Sets the value of the bbox property.
     *
     * @param value allowed object is
     *              {@link Bbox }
     */
    public void setBbox(Bbox value) {
        this.bbox = value;
    }

}
