//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Bbox complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Bbox">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}Geometri">
 *       &lt;sequence>
 *         &lt;element name="nedreVenstre" type="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}Koordinat"/>
 *         &lt;element name="oevreHoeyre" type="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}Koordinat"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bbox", namespace = "http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", propOrder = {
        "nedreVenstre",
        "oevreHoeyre"
})
public class Bbox
        extends Geometri {

    @XmlElement(required = true)
    protected Koordinat nedreVenstre;
    @XmlElement(required = true)
    protected Koordinat oevreHoeyre;

    /**
     * Gets the value of the nedreVenstre property.
     *
     * @return possible object is
     * {@link Koordinat }
     */
    public Koordinat getNedreVenstre() {
        return nedreVenstre;
    }

    /**
     * Sets the value of the nedreVenstre property.
     *
     * @param value allowed object is
     *              {@link Koordinat }
     */
    public void setNedreVenstre(Koordinat value) {
        this.nedreVenstre = value;
    }

    /**
     * Gets the value of the oevreHoeyre property.
     *
     * @return possible object is
     * {@link Koordinat }
     */
    public Koordinat getOevreHoeyre() {
        return oevreHoeyre;
    }

    /**
     * Sets the value of the oevreHoeyre property.
     *
     * @param value allowed object is
     *              {@link Koordinat }
     */
    public void setOevreHoeyre(Koordinat value) {
        this.oevreHoeyre = value;
    }

}
