//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for ByggIdent complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ByggIdent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bygningsNummer" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="endringsloepenummer" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ByggIdent", namespace = "http://rep.geointegrasjon.no/Matrikkel/Felles/xml.schema/2012.01.31", propOrder = {
        "bygningsNummer",
        "endringsloepenummer"
})
public class ByggIdent {

    @XmlElement(required = true)
    protected BigInteger bygningsNummer;
    protected BigInteger endringsloepenummer;

    /**
     * Gets the value of the bygningsNummer property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getBygningsNummer() {
        return bygningsNummer;
    }

    /**
     * Sets the value of the bygningsNummer property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setBygningsNummer(BigInteger value) {
        this.bygningsNummer = value;
    }

    /**
     * Gets the value of the endringsloepenummer property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getEndringsloepenummer() {
        return endringsloepenummer;
    }

    /**
     * Sets the value of the endringsloepenummer property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setEndringsloepenummer(BigInteger value) {
        this.endringsloepenummer = value;
    }

}
