//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EksternNoekkel complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EksternNoekkel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fagsystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noekkel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EksternNoekkel", namespace = "http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31", propOrder = {
        "fagsystem",
        "noekkel"
})
public class EksternNoekkel {

    @XmlElement(required = true)
    protected String fagsystem;
    protected String noekkel;

    /**
     * Gets the value of the fagsystem property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFagsystem() {
        return fagsystem;
    }

    /**
     * Sets the value of the fagsystem property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFagsystem(String value) {
        this.fagsystem = value;
    }

    /**
     * Gets the value of the noekkel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNoekkel() {
        return noekkel;
    }

    /**
     * Sets the value of the noekkel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNoekkel(String value) {
        this.noekkel = value;
    }

}
