//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnkelAdresse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EnkelAdresse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adressetype" type="{http://rep.geointegrasjon.no/Felles/Adresse/xml.schema/2012.01.31}EnkelAdressetype"/>
 *         &lt;element name="adresselinje1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="adresselinje2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="postadresse" type="{http://rep.geointegrasjon.no/Felles/Adresse/xml.schema/2012.01.31}PostadministrativeOmraader" minOccurs="0"/>
 *         &lt;element name="landkode" type="{http://rep.geointegrasjon.no/Felles/Adresse/xml.schema/2012.01.31}Landkode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnkelAdresse", namespace = "http://rep.geointegrasjon.no/Felles/Adresse/xml.schema/2012.01.31", propOrder = {
        "adressetype",
        "adresselinje1",
        "adresselinje2",
        "postadresse",
        "landkode"
})
public class EnkelAdresse {

    @XmlElement(required = true)
    protected EnkelAdressetype adressetype;
    protected String adresselinje1;
    protected String adresselinje2;
    protected PostadministrativeOmraader postadresse;
    protected Landkode landkode;

    /**
     * Gets the value of the adressetype property.
     *
     * @return possible object is
     * {@link EnkelAdressetype }
     */
    public EnkelAdressetype getAdressetype() {
        return adressetype;
    }

    /**
     * Sets the value of the adressetype property.
     *
     * @param value allowed object is
     *              {@link EnkelAdressetype }
     */
    public void setAdressetype(EnkelAdressetype value) {
        this.adressetype = value;
    }

    /**
     * Gets the value of the adresselinje1 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdresselinje1() {
        return adresselinje1;
    }

    /**
     * Sets the value of the adresselinje1 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdresselinje1(String value) {
        this.adresselinje1 = value;
    }

    /**
     * Gets the value of the adresselinje2 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdresselinje2() {
        return adresselinje2;
    }

    /**
     * Sets the value of the adresselinje2 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdresselinje2(String value) {
        this.adresselinje2 = value;
    }

    /**
     * Gets the value of the postadresse property.
     *
     * @return possible object is
     * {@link PostadministrativeOmraader }
     */
    public PostadministrativeOmraader getPostadresse() {
        return postadresse;
    }

    /**
     * Sets the value of the postadresse property.
     *
     * @param value allowed object is
     *              {@link PostadministrativeOmraader }
     */
    public void setPostadresse(PostadministrativeOmraader value) {
        this.postadresse = value;
    }

    /**
     * Gets the value of the landkode property.
     *
     * @return possible object is
     * {@link Landkode }
     */
    public Landkode getLandkode() {
        return landkode;
    }

    /**
     * Sets the value of the landkode property.
     *
     * @param value allowed object is
     *              {@link Landkode }
     */
    public void setLandkode(Landkode value) {
        this.landkode = value;
    }

}
