//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Filreferanse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Filreferanse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Arkiv/Dokument/xml.schema/2012.01.31}Fil">
 *       &lt;sequence>
 *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="kvitteringUri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Filreferanse", namespace = "http://rep.geointegrasjon.no/Arkiv/Dokument/xml.schema/2012.01.31", propOrder = {
        "uri",
        "kvitteringUri"
})
public class Filreferanse
        extends Fil {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String uri;
    @XmlSchemaType(name = "anyURI")
    protected String kvitteringUri;

    /**
     * Gets the value of the uri property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the kvitteringUri property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKvitteringUri() {
        return kvitteringUri;
    }

    /**
     * Sets the value of the kvitteringUri property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKvitteringUri(String value) {
        this.kvitteringUri = value;
    }

}
