//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ansvarlig" type="{http://rep.geointegrasjon.no/Felles/Filter/xml.schema/2012.01.31}Ansvarlig" minOccurs="0"/>
 *         &lt;element name="returnerMerknad" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="returnerTilleggsinformasjon" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="returnerKorrespondansepart" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="returnerAvskrivning" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="kontekst" type="{http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31}ArkivKontekst" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "ansvarlig",
        "returnerMerknad",
        "returnerTilleggsinformasjon",
        "returnerKorrespondansepart",
        "returnerAvskrivning",
        "kontekst"
})
@XmlRootElement(name = "FinnJournalposterUnderArbeid")
public class FinnJournalposterUnderArbeid {

    protected Ansvarlig ansvarlig;
    protected Boolean returnerMerknad;
    protected Boolean returnerTilleggsinformasjon;
    protected Boolean returnerKorrespondansepart;
    protected Boolean returnerAvskrivning;
    protected ArkivKontekst kontekst;

    /**
     * Gets the value of the ansvarlig property.
     *
     * @return possible object is
     * {@link Ansvarlig }
     */
    public Ansvarlig getAnsvarlig() {
        return ansvarlig;
    }

    /**
     * Sets the value of the ansvarlig property.
     *
     * @param value allowed object is
     *              {@link Ansvarlig }
     */
    public void setAnsvarlig(Ansvarlig value) {
        this.ansvarlig = value;
    }

    /**
     * Gets the value of the returnerMerknad property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isReturnerMerknad() {
        return returnerMerknad;
    }

    /**
     * Sets the value of the returnerMerknad property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReturnerMerknad(Boolean value) {
        this.returnerMerknad = value;
    }

    /**
     * Gets the value of the returnerTilleggsinformasjon property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isReturnerTilleggsinformasjon() {
        return returnerTilleggsinformasjon;
    }

    /**
     * Sets the value of the returnerTilleggsinformasjon property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReturnerTilleggsinformasjon(Boolean value) {
        this.returnerTilleggsinformasjon = value;
    }

    /**
     * Gets the value of the returnerKorrespondansepart property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isReturnerKorrespondansepart() {
        return returnerKorrespondansepart;
    }

    /**
     * Sets the value of the returnerKorrespondansepart property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReturnerKorrespondansepart(Boolean value) {
        this.returnerKorrespondansepart = value;
    }

    /**
     * Gets the value of the returnerAvskrivning property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isReturnerAvskrivning() {
        return returnerAvskrivning;
    }

    /**
     * Sets the value of the returnerAvskrivning property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setReturnerAvskrivning(Boolean value) {
        this.returnerAvskrivning = value;
    }

    /**
     * Gets the value of the kontekst property.
     *
     * @return possible object is
     * {@link ArkivKontekst }
     */
    public ArkivKontekst getKontekst() {
        return kontekst;
    }

    /**
     * Sets the value of the kontekst property.
     *
     * @param value allowed object is
     *              {@link ArkivKontekst }
     */
    public void setKontekst(ArkivKontekst value) {
        this.kontekst = value;
    }

}
