//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Flate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Flate">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}Geometri">
 *       &lt;sequence>
 *         &lt;element name="indreAvgrensning" type="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}RingListe" minOccurs="0"/>
 *         &lt;element name="ytreAvgrensning" type="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}Ring"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Flate", namespace = "http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", propOrder = {
        "indreAvgrensning",
        "ytreAvgrensning"
})
public class Flate
        extends Geometri {

    protected RingListe indreAvgrensning;
    @XmlElement(required = true)
    protected Ring ytreAvgrensning;

    /**
     * Gets the value of the indreAvgrensning property.
     *
     * @return possible object is
     * {@link RingListe }
     */
    public RingListe getIndreAvgrensning() {
        return indreAvgrensning;
    }

    /**
     * Sets the value of the indreAvgrensning property.
     *
     * @param value allowed object is
     *              {@link RingListe }
     */
    public void setIndreAvgrensning(RingListe value) {
        this.indreAvgrensning = value;
    }

    /**
     * Gets the value of the ytreAvgrensning property.
     *
     * @return possible object is
     * {@link Ring }
     */
    public Ring getYtreAvgrensning() {
        return ytreAvgrensning;
    }

    /**
     * Sets the value of the ytreAvgrensning property.
     *
     * @param value allowed object is
     *              {@link Ring }
     */
    public void setYtreAvgrensning(Ring value) {
        this.ytreAvgrensning = value;
    }

}
