//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for GeointegrasjonFault complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GeointegrasjonFault">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="feilKode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="feilBeskrivelse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="feilDetaljer" type="{http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31}StringListe" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeointegrasjonFault", namespace = "http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31", propOrder = {
        "feilKode",
        "feilBeskrivelse",
        "feilDetaljer"
})
@XmlSeeAlso({
        SystemFault.class,
        ApplicationFault.class
})
public class GeointegrasjonFault {

    @XmlElement(required = true)
    protected String feilKode;
    protected String feilBeskrivelse;
    protected StringListe feilDetaljer;

    /**
     * Gets the value of the feilKode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFeilKode() {
        return feilKode;
    }

    /**
     * Sets the value of the feilKode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFeilKode(String value) {
        this.feilKode = value;
    }

    /**
     * Gets the value of the feilBeskrivelse property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFeilBeskrivelse() {
        return feilBeskrivelse;
    }

    /**
     * Sets the value of the feilBeskrivelse property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFeilBeskrivelse(String value) {
        this.feilBeskrivelse = value;
    }

    /**
     * Gets the value of the feilDetaljer property.
     *
     * @return possible object is
     * {@link StringListe }
     */
    public StringListe getFeilDetaljer() {
        return feilDetaljer;
    }

    /**
     * Sets the value of the feilDetaljer property.
     *
     * @param value allowed object is
     *              {@link StringListe }
     */
    public void setFeilDetaljer(StringListe value) {
        this.feilDetaljer = value;
    }

}
