//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for Journalnummer complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Journalnummer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}Journpostnoekkel">
 *       &lt;sequence>
 *         &lt;element name="journalaar" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="journalsekvensnummer" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Journalnummer", namespace = "http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31", propOrder = {
        "journalaar",
        "journalsekvensnummer"
})
public class Journalnummer
        extends Journpostnoekkel {

    @XmlElement(required = true)
    protected BigInteger journalaar;
    @XmlElement(required = true)
    protected BigInteger journalsekvensnummer;

    /**
     * Gets the value of the journalaar property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getJournalaar() {
        return journalaar;
    }

    /**
     * Sets the value of the journalaar property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setJournalaar(BigInteger value) {
        this.journalaar = value;
    }

    /**
     * Gets the value of the journalsekvensnummer property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getJournalsekvensnummer() {
        return journalsekvensnummer;
    }

    /**
     * Sets the value of the journalsekvensnummer property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setJournalsekvensnummer(BigInteger value) {
        this.journalsekvensnummer = value;
    }

}
