//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Kode complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Kode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kodeverdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kodebeskrivelse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="erGyldig" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kode", namespace = "http://rep.geointegrasjon.no/Felles/Kodeliste/xml.schema/2012.01.31", propOrder = {
        "kodeverdi",
        "kodebeskrivelse",
        "erGyldig"
})
@XmlSeeAlso({
        Journalstatus.class,
        Saksstatus.class,
        Dokumentstatus.class,
        Variantformat.class,
        Format.class,
        Dokumenttype.class,
        TilknyttetRegistreringSom.class,
        KoordinatsystemKode.class,
        Arkivdel.class,
        Journalenhet.class,
        Informasjonstype.class,
        Tilgangsrestriksjon.class,
        Avskrivningsmaate.class,
        SkjermingOpphorerAksjon.class,
        SkjermingsHjemmel.class,
        Journalposttype.class,
        Korrespondanseparttype.class,
        Klassifikasjonssystem.class,
        SakspartRolle.class,
        Mappetype.class,
        Forsendelsesmaate.class,
        Dokumentmedium.class,
        Kassasjonsvedtak.class,
        PersonidentifikatorType.class,
        Landkode.class,
        EnkelAdressetype.class
})
public class Kode {

    @XmlElement(required = true)
    protected String kodeverdi;
    protected String kodebeskrivelse;
    protected Boolean erGyldig;

    /**
     * Gets the value of the kodeverdi property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKodeverdi() {
        return kodeverdi;
    }

    /**
     * Sets the value of the kodeverdi property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKodeverdi(String value) {
        this.kodeverdi = value;
    }

    /**
     * Gets the value of the kodebeskrivelse property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKodebeskrivelse() {
        return kodebeskrivelse;
    }

    /**
     * Sets the value of the kodebeskrivelse property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKodebeskrivelse(String value) {
        this.kodebeskrivelse = value;
    }

    /**
     * Gets the value of the erGyldig property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isErGyldig() {
        return erGyldig;
    }

    /**
     * Sets the value of the erGyldig property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setErGyldig(Boolean value) {
        this.erGyldig = value;
    }

}
