//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Kontekst complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Kontekst">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="spraak" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="klientnavn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="klientversjon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="systemversjon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kontekst", namespace = "http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31", propOrder = {
        "spraak",
        "klientnavn",
        "klientversjon",
        "systemversjon"
})
@XmlSeeAlso({
        ArkivKontekst.class,
        MatrikkelKontekst.class,
        PlanKontekst.class
})
public class Kontekst {

    protected String spraak;
    protected String klientnavn;
    protected String klientversjon;
    protected String systemversjon;

    /**
     * Gets the value of the spraak property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSpraak() {
        return spraak;
    }

    /**
     * Sets the value of the spraak property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSpraak(String value) {
        this.spraak = value;
    }

    /**
     * Gets the value of the klientnavn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKlientnavn() {
        return klientnavn;
    }

    /**
     * Sets the value of the klientnavn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKlientnavn(String value) {
        this.klientnavn = value;
    }

    /**
     * Gets the value of the klientversjon property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKlientversjon() {
        return klientversjon;
    }

    /**
     * Sets the value of the klientversjon property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKlientversjon(String value) {
        this.klientversjon = value;
    }

    /**
     * Gets the value of the systemversjon property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSystemversjon() {
        return systemversjon;
    }

    /**
     * Sets the value of the systemversjon property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSystemversjon(String value) {
        this.systemversjon = value;
    }

}
