//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Kontakt complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Kontakt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="navn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adresser" type="{http://rep.geointegrasjon.no/Felles/Adresse/xml.schema/2012.01.31}EnkelAdresseListe" minOccurs="0"/>
 *         &lt;element name="elektroniskeAdresser" type="{http://rep.geointegrasjon.no/Felles/Adresse/xml.schema/2012.01.31}ElektroniskAdresseListe" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kontakt", namespace = "http://rep.geointegrasjon.no/Felles/Kontakt/xml.schema/2012.01.31", propOrder = {
        "navn",
        "adresser",
        "elektroniskeAdresser"
})
@XmlSeeAlso({
        Organisasjon.class,
        Person.class
})
public class Kontakt {

    @XmlElement(required = true)
    protected String navn;
    protected EnkelAdresseListe adresser;
    protected ElektroniskAdresseListe elektroniskeAdresser;

    /**
     * Gets the value of the navn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNavn() {
        return navn;
    }

    /**
     * Sets the value of the navn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNavn(String value) {
        this.navn = value;
    }

    /**
     * Gets the value of the adresser property.
     *
     * @return possible object is
     * {@link EnkelAdresseListe }
     */
    public EnkelAdresseListe getAdresser() {
        return adresser;
    }

    /**
     * Sets the value of the adresser property.
     *
     * @param value allowed object is
     *              {@link EnkelAdresseListe }
     */
    public void setAdresser(EnkelAdresseListe value) {
        this.adresser = value;
    }

    /**
     * Gets the value of the elektroniskeAdresser property.
     *
     * @return possible object is
     * {@link ElektroniskAdresseListe }
     */
    public ElektroniskAdresseListe getElektroniskeAdresser() {
        return elektroniskeAdresser;
    }

    /**
     * Sets the value of the elektroniskeAdresser property.
     *
     * @param value allowed object is
     *              {@link ElektroniskAdresseListe }
     */
    public void setElektroniskeAdresser(ElektroniskAdresseListe value) {
        this.elektroniskeAdresser = value;
    }

}
