//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Koordinat complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Koordinat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="z" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Koordinat", namespace = "http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", propOrder = {
        "x",
        "y",
        "z"
})
public class Koordinat {

    protected double x;
    protected double y;
    protected Double z;

    /**
     * Gets the value of the x property.
     */
    public double getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     */
    public void setX(double value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     */
    public double getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     */
    public void setY(double value) {
        this.y = value;
    }

    /**
     * Gets the value of the z property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setZ(Double value) {
        this.z = value;
    }

}
