//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatrikkelKontekst complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MatrikkelKontekst">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31}Kontekst">
 *       &lt;sequence>
 *         &lt;element name="koordinatsystem" type="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}KoordinatsystemKode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatrikkelKontekst", namespace = "http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31", propOrder = {
        "koordinatsystem"
})
public class MatrikkelKontekst
        extends Kontekst {

    protected KoordinatsystemKode koordinatsystem;

    /**
     * Gets the value of the koordinatsystem property.
     *
     * @return possible object is
     * {@link KoordinatsystemKode }
     */
    public KoordinatsystemKode getKoordinatsystem() {
        return koordinatsystem;
    }

    /**
     * Sets the value of the koordinatsystem property.
     *
     * @param value allowed object is
     *              {@link KoordinatsystemKode }
     */
    public void setKoordinatsystem(KoordinatsystemKode value) {
        this.koordinatsystem = value;
    }

}
