//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for Matrikkelnummer complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Matrikkelnummer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kommunenummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gaardsnummer" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="bruksnummer" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="festenummer" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="seksjonsnummer" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Matrikkelnummer", namespace = "http://rep.geointegrasjon.no/Matrikkel/Felles/xml.schema/2012.01.31", propOrder = {
        "kommunenummer",
        "gaardsnummer",
        "bruksnummer",
        "festenummer",
        "seksjonsnummer"
})
public class Matrikkelnummer {

    @XmlElement(required = true)
    protected String kommunenummer;
    @XmlElement(required = true)
    protected BigInteger gaardsnummer;
    @XmlElement(required = true)
    protected BigInteger bruksnummer;
    protected BigInteger festenummer;
    protected BigInteger seksjonsnummer;

    /**
     * Gets the value of the kommunenummer property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKommunenummer() {
        return kommunenummer;
    }

    /**
     * Sets the value of the kommunenummer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKommunenummer(String value) {
        this.kommunenummer = value;
    }

    /**
     * Gets the value of the gaardsnummer property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getGaardsnummer() {
        return gaardsnummer;
    }

    /**
     * Sets the value of the gaardsnummer property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setGaardsnummer(BigInteger value) {
        this.gaardsnummer = value;
    }

    /**
     * Gets the value of the bruksnummer property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getBruksnummer() {
        return bruksnummer;
    }

    /**
     * Sets the value of the bruksnummer property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setBruksnummer(BigInteger value) {
        this.bruksnummer = value;
    }

    /**
     * Gets the value of the festenummer property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getFestenummer() {
        return festenummer;
    }

    /**
     * Sets the value of the festenummer property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setFestenummer(BigInteger value) {
        this.festenummer = value;
    }

    /**
     * Gets the value of the seksjonsnummer property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getSeksjonsnummer() {
        return seksjonsnummer;
    }

    /**
     * Sets the value of the seksjonsnummer property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setSeksjonsnummer(BigInteger value) {
        this.seksjonsnummer = value;
    }

}
