//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Merknad complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Merknad">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="systemID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merknadstekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="merknadstype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merknadsdato" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="merknadRegistrertAv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merknadRegistrertAvInit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Merknad", namespace = "http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31", propOrder = {
        "systemID",
        "merknadstekst",
        "merknadstype",
        "merknadsdato",
        "merknadRegistrertAv",
        "merknadRegistrertAvInit"
})
public class Merknad {

    protected String systemID;
    @XmlElement(required = true)
    protected String merknadstekst;
    protected String merknadstype;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar merknadsdato;
    protected String merknadRegistrertAv;
    protected String merknadRegistrertAvInit;

    /**
     * Gets the value of the systemID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSystemID() {
        return systemID;
    }

    /**
     * Sets the value of the systemID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSystemID(String value) {
        this.systemID = value;
    }

    /**
     * Gets the value of the merknadstekst property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMerknadstekst() {
        return merknadstekst;
    }

    /**
     * Sets the value of the merknadstekst property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMerknadstekst(String value) {
        this.merknadstekst = value;
    }

    /**
     * Gets the value of the merknadstype property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMerknadstype() {
        return merknadstype;
    }

    /**
     * Sets the value of the merknadstype property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMerknadstype(String value) {
        this.merknadstype = value;
    }

    /**
     * Gets the value of the merknadsdato property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getMerknadsdato() {
        return merknadsdato;
    }

    /**
     * Sets the value of the merknadsdato property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setMerknadsdato(XMLGregorianCalendar value) {
        this.merknadsdato = value;
    }

    /**
     * Gets the value of the merknadRegistrertAv property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMerknadRegistrertAv() {
        return merknadRegistrertAv;
    }

    /**
     * Sets the value of the merknadRegistrertAv property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMerknadRegistrertAv(String value) {
        this.merknadRegistrertAv = value;
    }

    /**
     * Gets the value of the merknadRegistrertAvInit property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMerknadRegistrertAvInit() {
        return merknadRegistrertAvInit;
    }

    /**
     * Sets the value of the merknadRegistrertAvInit property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMerknadRegistrertAvInit(String value) {
        this.merknadRegistrertAvInit = value;
    }

}
