//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tilleggsinfo" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}TilleggsinformasjonListe" minOccurs="0"/>
 *         &lt;element name="journalnokkel" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}Journpostnoekkel" minOccurs="0"/>
 *         &lt;element name="kontekst" type="{http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31}ArkivKontekst" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "tilleggsinfo",
        "journalnokkel",
        "kontekst"
})
@XmlRootElement(name = "NyJournalpostTilleggsinformasjon")
public class NyJournalpostTilleggsinformasjon {

    protected TilleggsinformasjonListe tilleggsinfo;
    protected Journpostnoekkel journalnokkel;
    protected ArkivKontekst kontekst;

    /**
     * Gets the value of the tilleggsinfo property.
     *
     * @return possible object is
     * {@link TilleggsinformasjonListe }
     */
    public TilleggsinformasjonListe getTilleggsinfo() {
        return tilleggsinfo;
    }

    /**
     * Sets the value of the tilleggsinfo property.
     *
     * @param value allowed object is
     *              {@link TilleggsinformasjonListe }
     */
    public void setTilleggsinfo(TilleggsinformasjonListe value) {
        this.tilleggsinfo = value;
    }

    /**
     * Gets the value of the journalnokkel property.
     *
     * @return possible object is
     * {@link Journpostnoekkel }
     */
    public Journpostnoekkel getJournalnokkel() {
        return journalnokkel;
    }

    /**
     * Sets the value of the journalnokkel property.
     *
     * @param value allowed object is
     *              {@link Journpostnoekkel }
     */
    public void setJournalnokkel(Journpostnoekkel value) {
        this.journalnokkel = value;
    }

    /**
     * Gets the value of the kontekst property.
     *
     * @return possible object is
     * {@link ArkivKontekst }
     */
    public ArkivKontekst getKontekst() {
        return kontekst;
    }

    /**
     * Sets the value of the kontekst property.
     *
     * @param value allowed object is
     *              {@link ArkivKontekst }
     */
    public void setKontekst(ArkivKontekst value) {
        this.kontekst = value;
    }

}
