//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Omraade complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Omraade">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="punkt" type="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}Punkt" minOccurs="0"/>
 *         &lt;element name="flate" type="{http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31}Flate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Omraade", namespace = "http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", propOrder = {
        "punkt",
        "flate"
})
public class Omraade {

    protected Punkt punkt;
    protected Flate flate;

    /**
     * Gets the value of the punkt property.
     *
     * @return possible object is
     * {@link Punkt }
     */
    public Punkt getPunkt() {
        return punkt;
    }

    /**
     * Sets the value of the punkt property.
     *
     * @param value allowed object is
     *              {@link Punkt }
     */
    public void setPunkt(Punkt value) {
        this.punkt = value;
    }

    /**
     * Gets the value of the flate property.
     *
     * @return possible object is
     * {@link Flate }
     */
    public Flate getFlate() {
        return flate;
    }

    /**
     * Sets the value of the flate property.
     *
     * @param value allowed object is
     *              {@link Flate }
     */
    public void setFlate(Flate value) {
        this.flate = value;
    }

}
