//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Person complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Person">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Felles/Kontakt/xml.schema/2012.01.31}Kontakt">
 *       &lt;sequence>
 *         &lt;element name="personid" type="{http://rep.geointegrasjon.no/Felles/Kontakt/xml.schema/2012.01.31}Personidentifikator" minOccurs="0"/>
 *         &lt;element name="etternavn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fornavn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person", namespace = "http://rep.geointegrasjon.no/Felles/Kontakt/xml.schema/2012.01.31", propOrder = {
        "personid",
        "etternavn",
        "fornavn"
})
public class Person
        extends Kontakt {

    protected Personidentifikator personid;
    protected String etternavn;
    protected String fornavn;

    /**
     * Gets the value of the personid property.
     *
     * @return possible object is
     * {@link Personidentifikator }
     */
    public Personidentifikator getPersonid() {
        return personid;
    }

    /**
     * Sets the value of the personid property.
     *
     * @param value allowed object is
     *              {@link Personidentifikator }
     */
    public void setPersonid(Personidentifikator value) {
        this.personid = value;
    }

    /**
     * Gets the value of the etternavn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEtternavn() {
        return etternavn;
    }

    /**
     * Sets the value of the etternavn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEtternavn(String value) {
        this.etternavn = value;
    }

    /**
     * Gets the value of the fornavn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFornavn() {
        return fornavn;
    }

    /**
     * Sets the value of the fornavn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFornavn(String value) {
        this.fornavn = value;
    }

}
