//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Personidentifikator complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Personidentifikator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="personidentifikatorNr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="personidentifikatorType" type="{http://rep.geointegrasjon.no/Felles/Kontakt/xml.schema/2012.01.31}PersonidentifikatorType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Personidentifikator", namespace = "http://rep.geointegrasjon.no/Felles/Kontakt/xml.schema/2012.01.31", propOrder = {
        "personidentifikatorNr",
        "personidentifikatorType"
})
public class Personidentifikator {

    protected String personidentifikatorNr;
    protected PersonidentifikatorType personidentifikatorType;

    /**
     * Gets the value of the personidentifikatorNr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPersonidentifikatorNr() {
        return personidentifikatorNr;
    }

    /**
     * Sets the value of the personidentifikatorNr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPersonidentifikatorNr(String value) {
        this.personidentifikatorNr = value;
    }

    /**
     * Gets the value of the personidentifikatorType property.
     *
     * @return possible object is
     * {@link PersonidentifikatorType }
     */
    public PersonidentifikatorType getPersonidentifikatorType() {
        return personidentifikatorType;
    }

    /**
     * Sets the value of the personidentifikatorType property.
     *
     * @param value allowed object is
     *              {@link PersonidentifikatorType }
     */
    public void setPersonidentifikatorType(PersonidentifikatorType value) {
        this.personidentifikatorType = value;
    }

}
