//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sakspart complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Sakspart">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="systemID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="skjermetSakspart" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="kortnavn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kontaktperson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sakspartRolle" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}SakspartRolle" minOccurs="0"/>
 *         &lt;element name="merknad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Kontakt" type="{http://rep.geointegrasjon.no/Felles/Kontakt/xml.schema/2012.01.31}Kontakt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sakspart", namespace = "http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31", propOrder = {
        "systemID",
        "skjermetSakspart",
        "kortnavn",
        "kontaktperson",
        "sakspartRolle",
        "merknad",
        "kontakt"
})
public class Sakspart {

    protected String systemID;
    protected Boolean skjermetSakspart;
    protected String kortnavn;
    protected String kontaktperson;
    protected SakspartRolle sakspartRolle;
    protected String merknad;
    @XmlElement(name = "Kontakt", required = true)
    protected Kontakt kontakt;

    /**
     * Gets the value of the systemID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSystemID() {
        return systemID;
    }

    /**
     * Sets the value of the systemID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSystemID(String value) {
        this.systemID = value;
    }

    /**
     * Gets the value of the skjermetSakspart property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isSkjermetSakspart() {
        return skjermetSakspart;
    }

    /**
     * Sets the value of the skjermetSakspart property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setSkjermetSakspart(Boolean value) {
        this.skjermetSakspart = value;
    }

    /**
     * Gets the value of the kortnavn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKortnavn() {
        return kortnavn;
    }

    /**
     * Sets the value of the kortnavn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKortnavn(String value) {
        this.kortnavn = value;
    }

    /**
     * Gets the value of the kontaktperson property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKontaktperson() {
        return kontaktperson;
    }

    /**
     * Sets the value of the kontaktperson property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKontaktperson(String value) {
        this.kontaktperson = value;
    }

    /**
     * Gets the value of the sakspartRolle property.
     *
     * @return possible object is
     * {@link SakspartRolle }
     */
    public SakspartRolle getSakspartRolle() {
        return sakspartRolle;
    }

    /**
     * Sets the value of the sakspartRolle property.
     *
     * @param value allowed object is
     *              {@link SakspartRolle }
     */
    public void setSakspartRolle(SakspartRolle value) {
        this.sakspartRolle = value;
    }

    /**
     * Gets the value of the merknad property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMerknad() {
        return merknad;
    }

    /**
     * Sets the value of the merknad property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMerknad(String value) {
        this.merknad = value;
    }

    /**
     * Gets the value of the kontakt property.
     *
     * @return possible object is
     * {@link Kontakt }
     */
    public Kontakt getKontakt() {
        return kontakt;
    }

    /**
     * Sets the value of the kontakt property.
     *
     * @param value allowed object is
     *              {@link Kontakt }
     */
    public void setKontakt(Kontakt value) {
        this.kontakt = value;
    }

}
