//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for Saksnummer complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Saksnummer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Arkiv/Felles/xml.schema/2012.01.31}Saksnoekkel">
 *       &lt;sequence>
 *         &lt;element name="saksaar" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="sakssekvensnummer" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Saksnummer", namespace = "http://rep.geointegrasjon.no/Arkiv/Felles/xml.schema/2012.01.31", propOrder = {
        "saksaar",
        "sakssekvensnummer"
})
public class Saksnummer
        extends Saksnoekkel {

    @XmlElement(required = true)
    protected BigInteger saksaar;
    @XmlElement(required = true)
    protected BigInteger sakssekvensnummer;

    /**
     * Gets the value of the saksaar property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getSaksaar() {
        return saksaar;
    }

    /**
     * Sets the value of the saksaar property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setSaksaar(BigInteger value) {
        this.saksaar = value;
    }

    /**
     * Gets the value of the sakssekvensnummer property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getSakssekvensnummer() {
        return sakssekvensnummer;
    }

    /**
     * Sets the value of the sakssekvensnummer property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setSakssekvensnummer(BigInteger value) {
        this.sakssekvensnummer = value;
    }

}
