//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Skjerming complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Skjerming">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tilgangsrestriksjon" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}Tilgangsrestriksjon" minOccurs="0"/>
 *         &lt;element name="skjermingshjemmel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="skjermingOpphoererDato" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="skjermingOpphoererAksjon" type="{http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31}SkjermingOpphorerAksjon" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Skjerming", namespace = "http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31", propOrder = {
        "tilgangsrestriksjon",
        "skjermingshjemmel",
        "skjermingOpphoererDato",
        "skjermingOpphoererAksjon"
})
public class Skjerming {

    protected Tilgangsrestriksjon tilgangsrestriksjon;
    protected String skjermingshjemmel;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar skjermingOpphoererDato;
    protected SkjermingOpphorerAksjon skjermingOpphoererAksjon;

    /**
     * Gets the value of the tilgangsrestriksjon property.
     *
     * @return possible object is
     * {@link Tilgangsrestriksjon }
     */
    public Tilgangsrestriksjon getTilgangsrestriksjon() {
        return tilgangsrestriksjon;
    }

    /**
     * Sets the value of the tilgangsrestriksjon property.
     *
     * @param value allowed object is
     *              {@link Tilgangsrestriksjon }
     */
    public void setTilgangsrestriksjon(Tilgangsrestriksjon value) {
        this.tilgangsrestriksjon = value;
    }

    /**
     * Gets the value of the skjermingshjemmel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSkjermingshjemmel() {
        return skjermingshjemmel;
    }

    /**
     * Sets the value of the skjermingshjemmel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSkjermingshjemmel(String value) {
        this.skjermingshjemmel = value;
    }

    /**
     * Gets the value of the skjermingOpphoererDato property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getSkjermingOpphoererDato() {
        return skjermingOpphoererDato;
    }

    /**
     * Sets the value of the skjermingOpphoererDato property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setSkjermingOpphoererDato(XMLGregorianCalendar value) {
        this.skjermingOpphoererDato = value;
    }

    /**
     * Gets the value of the skjermingOpphoererAksjon property.
     *
     * @return possible object is
     * {@link SkjermingOpphorerAksjon }
     */
    public SkjermingOpphorerAksjon getSkjermingOpphoererAksjon() {
        return skjermingOpphoererAksjon;
    }

    /**
     * Sets the value of the skjermingOpphoererAksjon property.
     *
     * @param value allowed object is
     *              {@link SkjermingOpphorerAksjon }
     */
    public void setSkjermingOpphoererAksjon(SkjermingOpphorerAksjon value) {
        this.skjermingOpphoererAksjon = value;
    }

}
