//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SoekeOperatorEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SoekeOperatorEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LT"/>
 *     &lt;enumeration value="LE"/>
 *     &lt;enumeration value="EQ"/>
 *     &lt;enumeration value="GE"/>
 *     &lt;enumeration value="GT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "SoekeOperatorEnum", namespace = "http://rep.geointegrasjon.no/Felles/Filter/xml.schema/2012.01.31")
@XmlEnum
public enum SoekeOperatorEnum {

    LT,
    LE,
    EQ,
    GE,
    GT;

    public static SoekeOperatorEnum fromValue(String v) {
        return valueOf(v);
    }

    public String value() {
        return name();
    }

}
