//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Soekefelt complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Soekefelt">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Felles/Filter/xml.schema/2012.01.31}Kriterie">
 *       &lt;sequence>
 *         &lt;element name="feltnavn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="feltverdi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Soekefelt", namespace = "http://rep.geointegrasjon.no/Felles/Filter/xml.schema/2012.01.31", propOrder = {
        "feltnavn",
        "feltverdi"
})
public class Soekefelt
        extends Kriterie {

    @XmlElement(required = true)
    protected String feltnavn;
    @XmlElement(required = true)
    protected String feltverdi;

    /**
     * Gets the value of the feltnavn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFeltnavn() {
        return feltnavn;
    }

    /**
     * Sets the value of the feltnavn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFeltnavn(String value) {
        this.feltnavn = value;
    }

    /**
     * Gets the value of the feltverdi property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFeltverdi() {
        return feltverdi;
    }

    /**
     * Sets the value of the feltverdi property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFeltverdi(String value) {
        this.feltverdi = value;
    }

}
