//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:19:55 PM CEST 
//


package nikita.common.rep;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Stat complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Stat">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rep.geointegrasjon.no/Plan/Felles/xml.schema/2012.01.31}Administrativenhetsnummer">
 *       &lt;sequence>
 *         &lt;element name="landskode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Stat", namespace = "http://rep.geointegrasjon.no/Plan/Felles/xml.schema/2012.01.31", propOrder = {
        "landskode"
})
public class Stat
        extends Administrativenhetsnummer {

    @XmlElement(required = true)
    protected String landskode;

    /**
     * Gets the value of the landskode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLandskode() {
        return landskode;
    }

    /**
     * Sets the value of the landskode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLandskode(String value) {
        this.landskode = value;
    }

}
