# ===================================================================
# Spring Boot configuration for the "sqllite" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

server:
  application:
    name: OsloMet Noark 5 Core (Demo mode)
  contextPath: /noark5v4
  port: 8092

#spring.jpa.hibernate.ddl-auto=update

spring:
  datasource:
    url: jdbc:sqlite:test.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.SQLiteDialect
        integration:
          envers:
            enabled: false
        listeners:
          envers:
            autoRegister: false

management:
    context-path: /management
info:
    app.name: OsloMet Noark 5 Core (Demo mode)
    build.version: ${project.version}
hateoas:
    publicAddress: http://localhost:8092/noark5v4

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

nikita-noark5-core:
    pagination:
      _maxPageSize: 10
    mail:
        from: nikita@example.com
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: nikitaNoark5Core
        logs: # report metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        level:
            ROOT: DEBUG
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
    persistence:
         jpa.generateDdl: true
         # For Feide login
    saml:
         entityId: no:hioa:nikita:noark5

         idPUrl: http://nikita.hioa.no
         idPMetadata: https://idp-test.feide.no/simplesaml/saml2/idp/administration.php
    server:
         name: nikita.hioa.no
    details:
        conformity-levels:
            official: arkivstruktur, casehandling, metadata
            non-official: gui, import-api
    storage:
        location: /tmp/dokumenter
    checksumAlgorithm: SHA-256
